### ISSUE TITLE
caver-java cli generates class using deprecated api

### ISSUE THREAD

**Issue by NodeJupiter** [klaytn/caver-java#355]
Dependency
 - (gradle) com.klaytn.caver:core:1.9.0
 - (cli) caver-java 1.9.0, manually built.

Q. 1
I generated a java class with caver-java cli. 
but with this, creates class with deprecated api (extends SmartContract, KlayCredentials, KlayTransactionReceipt...)
I downloaded caver-java 1.9.0 source code zip from release tab

Q. 2
And deploying contract with generated class is impossible.
It throws NullPointerException.
is this sdk's bug?

java.lang.NullPointerException: Cannot invoke "com.klaytn.caver.Klay.getTransactionCount(String, org.web3j.protocol.core.DefaultBlockParameter)" because the return value of "com.klaytn.caver.Caver.klay()" is null
	at com.klaytn.caver.tx.manager.GetNonceProcessor.getNonce(GetNonceProcessor.java:39) ~[core-1.9.0.jar:na]
	at com.klaytn.caver.tx.manager.TransactionManager.sign(TransactionManager.java:176) ~[core-1.9.0.jar:na]
	at com.klaytn.caver.tx.manager.TransactionManager.executeTransaction(TransactionManager.java:74) ~[core-1.9.0.jar:na]
	at com.klaytn.caver.tx.ManagedTransaction.send(ManagedTransaction.java:51) ~[core-1.9.0.jar:na]
	at com.klaytn.caver.tx.SmartContract.executeTransaction(SmartContract.java:392) ~[core-1.9.0.jar:na]
	at com.klaytn.caver.tx.SmartContract.create(SmartContract.java:422) ~[core-1.9.0.jar:na]
	at com.klaytn.caver.tx.SmartContract.deploy(SmartContract.java:451) ~[core-1.9.0.jar:na]
	at com.klaytn.caver.tx.SmartContract.lambda$deployRemoteCall$10(SmartContract.java:499) ~[core-1.9.0.jar:na]
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42) ~[core-4.8.8.jar:na]
        ~~

**Comment by kjeom** [comment]
@NodeJupiter Hi, I have analyzed the `NullPointerException` and figure it out the exception occurs when the sender or feePayer is not added to `caver.wallet`.

Can you try again with caver.wallet that include the credential?

**Comment by kjeom** [comment]
@NodeJupiter Can I get a sample contract?

**Comment by NodeJupiter** [comment]
```sol
// SPDX-License-Identifier: UNLICENSED

pragma solidity ^0.8.7;

import "@klaytn/contracts/contracts/KIP/token/KIP37/KIP37.sol";
import "@klaytn/contracts/contracts/utils/Counters.sol";  

contract TestContract is KIP37 {

    mapping (uint256 => string) private _tokenUriMap;
    
    using Counters for Counters.Counter; 
    Counters.Counter private _tokenId; 

    address private owner;

    constructor() KIP37("") {
        owner = msg.sender;

        _tokenId.increment();
    }

    modifier restricted() {
        require(msg.sender == owner, "This function is restricted to the contract's owner");
        _;
    }

    function uri(uint256 tokenId) override public view returns (string memory) { 
        return(_tokenUriMap[tokenId]);
    } 

    function mintToken(string memory tokenURI, uint256 amount, bytes memory data) public restricted returns(uint256) { 
        uint256 newItemId = _tokenId.current(); 
        _mint(msg.sender, newItemId, amount, data);
        _setTokenUri(newItemId, tokenURI); 
        _tokenId.increment();
        return newItemId; 
    } 

    function _setTokenUri(uint256 tokenId, string memory tokenURI) private {
         _tokenUriMap[tokenId] = tokenURI; 
    } 

}
```

**Comment by kjeom** [comment]
@NodeJupiter I tested your code snippets

You can deploy `Caver` instance created by following.

```java
Caver caver = Caver.build(Caver.DEFAULT_URL);
```
